[versions]
#plugins
kotlin = "2.3.0"
agp = "8.13.2"

#libraries
activity = "1.12.2"
androidUtilities = "LOCAL"
core = "1.7.0"
coreKtx = "1.17.0"
appcompat = "1.7.1"
coreTesting = "2.2.0"
lifecycleRuntimeKtx = "2.10.0"
lifecycleLivedataKtx = "2.10.0"
lifecycleViewmodelKtx = "2.10.0"
lifecycleService = "2.10.0"
material = "1.13.0"
constraintLayout = "2.2.1"
lifecycle = "2.2.0"
coroutinesTest = "1.10.2"
junit = "4.13.2"
androidxJunit = "1.3.0"
espressoCore = "3.7.0"
mockitoKotlin = "2.2.0"
mockitoInline = "5.2.0"
recyclerview = "1.4.0"
robolectric = "4.16"
activityVersion = "1.12.2"
viewbinding = "8.13.2"

[libraries]
android-utilities = { module = "com.github.toyota-m2k:android-utilities", version.ref = "androidUtilities" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activity" }
core = { module = "androidx.test:core", version.ref = "core" }
core-testing = { module = "androidx.arch.core:core-testing", version.ref = "coreTesting" }
coreKtx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutinesTest" }
lifecycleService = { module = "androidx.lifecycle:lifecycle-service", version.ref = "lifecycleService" }
lifecycleViewmodelKtx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
lifecycleLivedataKtx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
lifecycleRuntimeKtx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
material = { module = "com.google.android.material:material", version.ref = "material" }
constraintLayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintLayout" }
lifecycleExtensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycle" }
junit = { module = "junit:junit", version.ref = "junit" }
androidxJunit = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
espressoCore = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
mockito-inline = { module = "org.mockito:mockito-inline", version.ref = "mockitoInline" }
mockito-kotlin = { module = "com.nhaarman.mockitokotlin2:mockito-kotlin", version.ref = "mockitoKotlin" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activityVersion" }
androidx-viewbinding = { group = "androidx.databinding", name = "viewbinding", version.ref = "viewbinding" }

[plugins]
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
